### PR TITLE
Added economic releases system

### PR DESCRIPTION
**Pull request by qusma**
OK, so this almost takes care of #3

Switched to 2-letter country codes and 3-letter currency codes as requested.

What this includes:

- Added EconomicReleases table to the db
- Broker for economic releases
- Job type and UI to schedule automatic updates of economic releases (also renamed job details to job settings, because that's what they are)
- FXStreet source for the events (grabs them from here: https://fxstreet.com/economic-calendar)
- Tests for the above

What's missing:

- There's no way to request this data from the client yet, it'll get added with the http networking

### CODE REVIEW

**Comment by leo90skk** [comment]
Thanks for your work!

Just a view thinks I think we should change:
* the new table `EconomicReleases` has the primary key with the fields `DateTime`, `Name` and `Country`. Can we make a primary key with an increment integer and use a unique index/key secure data integrity? This will make identification for each record easier.
* you use a static programmed table for all countries. I would like to have this in the database and fill it with the database Seed function. As we can see in the [ISO 3166-1 Changes](https://en.wikipedia.org/wiki/ISO_3166-1#Changes) list, changes still happen. The newest change will release next month.
* the same for the relation between countries and currencies. I heard that Poland want to join the EUR area. When this will happen, we should give the user the flexibility to change it without having to modify the source code.

Thanks so far.

**Comment by qusma** [comment]
Yeah good point with the countries. One table for everything or one each for countries/currencies?

**Comment by leo90skk** [comment]
I think we can make it like this for now:
- one table with country iso code, country name and current currency.
- maybe one table with just all currency iso codes and names

For long historical data one should use a data source provider that delivers the currency code, too.

**Comment by qusma** [comment]
>For long historical data one should use a data source provider that delivers the currency code, too.

What do you mean?

**Comment by qusma** [comment]
Apparently AddOrUpdate() doesn't work if you add two duplicate entries before calling SaveChanges()...

**Comment by leo90skk** [comment]
> What do you mean? A source for historical changes in currencies?

Yes.
If you would use a historical economic release calender data source with a long history, you would get in trouble when you link the currency from a country table with the current used currency.

*Example:* The countries [Lithuania](https://en.wikipedia.org/wiki/Lithuania) and [Latvia](https://en.wikipedia.org/wiki/Latvia) joined the EUR in 2014 and 2015. When you now use a economic release calender before that date, the software would use the currency code EUR instead of the currency that was yield at that time (LTL, LVL).

But I guess when you trade with such currencies, you will probably know about that and change the field current currency in the country table when the currency changes. For me that's god enough. I just wanna notice that.

**Pull request merged**
